@startuml
title warmhouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь")
Person(admin, "Administrator", "Работник настраивающий работу системы")

System(WarmHouseSystem, "WarmHouse", "Управляет, настраивает и мониторит датчики. Взаимодействует с БД. Выдаёт логи ошибок")

System_Ext(api, "API sensors of temperature", "Получение информации об изменении температуры на датчиках")

Rel(user, WarmHouseSystem, "Использует систему для мониторинга через Web приложение")
Rel(admin,WarmHouseSystem,"Подключает устройства к системе")
Rel(WarmHouseSystem,api,"Собирает информацию по обновлениям температуры")

@enduml